- name: Create a jenkins user
  user:
    name: jenkins
    password: '*'
    groups: # Empty by default, here we give it some groups
      - docker
      - google-sudoers
    state: present
    shell: /bin/bash       # Defaults to /bin/bash
    system: no             # Defaults to no
    createhome: yes        # Defaults to yes
    home: /home/jenkins    # Defaults to /home/<username>
